In [553]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

import torch
from torch import nn

### read data

In [554]:
train = pd.read_csv('train2.csv')
test = pd.read_csv('test2.csv')

In [555]:
train.head()

row_id  country  store  product  num_sold  year  quarter  month  day  \
0       0        0      0        1       329  2015        1      1    1   
1       1        0      0        0       520  2015        1      1    1   
2       2        0      0        2       146  2015        1      1    1   
3       3        0      1        1       572  2015        1      1    1   
4       5        0      1        2       283  2015        1      1    1   

   dayofweek  dayofmonth  dayofyear  weekofyear  weekday  is_weekend  
0          3          31          1           1        3           0  
1          3          31          1           1        3           0  
2          3          31          1           1        3           0  
3          3          31          1           1        3           0  
4          3          31          1           1        3           0

### data preprocessing

In [556]:
train = train.set_index('row_id')
test = test.set_index('row_id')


In [557]:
train

country  store  product  num_sold  year  quarter  month  day  \
row_id                                                                 
0             0      0        1       329  2015        1      1    1   
1             0      0        0       520  2015        1      1    1   
2             0      0        2       146  2015        1      1    1   
3             0      1        1       572  2015        1      1    1   
5             0      1        2       283  2015        1      1    1   
...         ...    ...      ...       ...   ...      ...    ...  ...   
26288         1      0        2       351  2018        4     12   31   
26291         1      1        2       561  2018        4     12   31   
26292         2      0        1       570  2018        4     12   31   
26294         2      0        2       250  2018        4     12   31   
26297         2      1        2       388  2018        4     12   31   

        dayofweek  dayofmonth  dayofyear  weekofyear  weekday  is_weekend  
row_id                                                                     
0               3          31          1           1        3           0  
1               3          31          1           1        3           0  
2               3          31          1           1        3           0  
3               3          31          1           1        3           0  
5               3          31          1           1        3           0  
...           ...         ...        ...         ...      ...         ...  
26288           0          31        365           1        0           0  
26291           0          31        365           1        0           0  
26292           0          31        365           1        0           0  
26294           0          31        365           1        0           0  
26297           0          31        365           1        0           0  

[24231 rows x 14 columns]

In [558]:
x_data = train.drop('num_sold', axis=1)
y_data = train.num_sold
std = StandardScaler()
x_data = std.fit_transform(x_data)
test = std.transform(test)

In [559]:
x_data

array([[-1.18528343, -0.9310183 , -0.10132783, ..., -1.73789137,
         0.02622937, -0.61164274],
       [-1.18528343, -0.9310183 , -1.3552986 , ..., -1.73789137,
         0.02622937, -0.61164274],
       [-1.18528343, -0.9310183 ,  1.15264293, ..., -1.73789137,
         0.02622937, -0.61164274],
       ...,
       [ 1.21259616, -0.9310183 , -0.10132783, ..., -1.73789137,
        -1.48222916, -0.61164274],
       [ 1.21259616, -0.9310183 ,  1.15264293, ..., -1.73789137,
        -1.48222916, -0.61164274],
       [ 1.21259616,  1.07409275,  1.15264293, ..., -1.73789137,
        -1.48222916, -0.61164274]])

In [560]:
x_data = torch.tensor(x_data, dtype=torch.float32)
test = torch.tensor(test, dtype=torch.float32)

y_data = torch.tensor(y_data, dtype=torch.float32)

In [561]:
print(x_data[:10])

print(x_data.shape)

tensor([[-1.1853, -0.9310, -0.1013, -1.3283, -1.3771, -1.6330, -1.6768,  0.0262,
          0.6824, -1.7619, -1.7379,  0.0262, -0.6116],
        [-1.1853, -0.9310, -1.3553, -1.3283, -1.3771, -1.6330, -1.6768,  0.0262,
          0.6824, -1.7619, -1.7379,  0.0262, -0.6116],
        [-1.1853, -0.9310,  1.1526, -1.3283, -1.3771, -1.6330, -1.6768,  0.0262,
          0.6824, -1.7619, -1.7379,  0.0262, -0.6116],
        [-1.1853,  1.0741, -0.1013, -1.3283, -1.3771, -1.6330, -1.6768,  0.0262,
          0.6824, -1.7619, -1.7379,  0.0262, -0.6116],
        [-1.1853,  1.0741,  1.1526, -1.3283, -1.3771, -1.6330, -1.6768,  0.0262,
          0.6824, -1.7619, -1.7379,  0.0262, -0.6116],
        [ 0.0137, -0.9310, -0.1013, -1.3283, -1.3771, -1.6330, -1.6768,  0.0262,
          0.6824, -1.7619, -1.7379,  0.0262, -0.6116],
        [ 0.0137, -0.9310,  1.1526, -1.3283, -1.3771, -1.6330, -1.6768,  0.0262,
          0.6824, -1.7619, -1.7379,  0.0262, -0.6116],
        [ 0.0137,  1.0741,  1.1526, -1.3283, -1.

### model train

In [562]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data)

In [563]:
# np.unique(y_train.detach().numpy())

In [564]:
from torch.utils.data import TensorDataset

In [565]:
from torch.utils.data import DataLoader

In [566]:
dataset_train = TensorDataset(x_train, y_train)
loader_train = DataLoader(dataset_train, batch_size=256, shuffle=True)

dataset_test = TensorDataset(x_test, y_test)
loader_test = DataLoader(dataset_test, batch_size=256, shuffle=True)


In [567]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using {device} device')

Using cuda device


In [584]:
import torch.nn.functional as F
n_feature = 13
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(n_feature, n_feature*2)
        # self.fc2 = nn.Linear(n_feature*2, n_feature*4)
        # self.bn1 = nn.BatchNorm1d(n_feature*2)
        # self.fc3 = nn.Linear(n_feature*4, n_feature*8)
        # self.fc4 = nn.Linear(n_feature*8, n_feature*16)
        # self.bn2 = nn.BatchNorm1d(n_feature*16)
        # self.fc5 = nn.Linear(n_feature*16, n_feature*32)
        # self.fc6 = nn.Linear(n_feature*32, n_feature*64)
        # self.fc7 = nn.Linear(n_feature*64, n_feature*128)
        # self.bn3 = nn.BatchNorm1d(n_feature*128)
        # self.fc8 = nn.Linear(n_feature*128, n_feature*64)
        # self.fc9 = nn.Linear(n_feature*64, n_feature*32)
        # self.fc10 = nn.Linear(n_feature*32, n_feature*16)
        # self.bn4 = nn.BatchNorm1d(n_feature*16)
        # self.fc11 = nn.Linear(n_feature*16, n_feature*8)
        # self.fc12 = nn.Linear(n_feature*8, n_feature*4)
        # self.bn5 = nn.BatchNorm1d(n_feature*4)
        # self.fc13 = nn.Linear(n_feature*4, n_feature*2)
        self.fc14 = nn.Linear(n_feature*2, n_feature)
        self.fc15 = nn.Linear(n_feature, 1)

        # self.fc1 = nn.Linear(n_feature, n_feature*2)
        # self.bn1 = nn.BatchNorm1d(n_feature*2)
        # self.fc2 = nn.Linear(n_feature*2, n_feature*4)
        # self.bn2 = nn.BatchNorm1d(n_feature*4)
        # self.fc3 = nn.Linear(n_feature*4, n_feature*8)
        # self.bn3 = nn.BatchNorm1d(n_feature*8)
        # self.fc4 = nn.Linear(n_feature*8, n_feature*4)
        # self.fc5 = nn.Linear(n_feature*4, n_feature*2)
        # self.bn5 = nn.BatchNorm1d(n_feature*2)
        # self.fc6 = nn.Linear(n_feature*2, n_feature)
        # self.fc7 = nn.Linear(n_feature,  1)


    def forward(self, x):
        x = F.relu(self.fc1(x))
        # x = F.relu(self.fc2(x))
        # x = self.bn1(x)

        # x = F.relu(self.fc3(x))
        # x = F.relu(self.fc4(x))
        # x = self.bn2(x)
        # x = F.relu(self.fc5(x)) 
        # x = F.relu(self.fc6(x) )
        # x = F.relu(self.fc7(x) )
        # x = self.bn3(x) 
        # x = F.relu(self.fc8(x) )
        # x = F.relu(self.fc9(x) )
        # x = F.relu(self.fc10(x) )
        # x = self.bn4(x)
        # x = F.relu(self.fc11(x) )
        # x = F.relu(self.fc12(x) )
        # x = self.bn5(x) 
        # x = F.relu(self.fc13(x) )
        x = F.relu(self.fc14(x))
        x = self.fc15(x) 
        # x = self.fc1(x)
        # x = F.relu(self.bn1(x))
        # x = F.relu(self.fc2(x))
        # x= F.relu(self.bn2(x) )
        # x= F.relu(self.fc3(x) )
        # x= F.relu(self.bn3(x) )
        # x= F.relu(self.fc4(x) )
        # x = F.relu(self.fc5(x))
        # x = F.relu(self.bn5(x))
        # x = F.relu(self.fc6(x))
        # x = self.fc7(x)
        # x = self.fc8(x)


        
        return x

In [585]:
model = NeuralNetwork().to(device)
# model.apply(init_weights)
print(model)

NeuralNetwork(
  (fc1): Linear(in_features=13, out_features=26, bias=True)
  (fc14): Linear(in_features=26, out_features=13, bias=True)
  (fc15): Linear(in_features=13, out_features=1, bias=True)
)


In [586]:
learning_rate = 0.001
batch_size = 64
epochs = 300

In [587]:
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        
        X = X.to(device)
        y = y.to(device)
        
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        # scheduler.step()
        optimizer.step()

    loss = loss.item()
    loss = loss ** 0.5
    print(f"loss: {loss:>7f}")


def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            
            X = X.to(device)
            y = y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()

    test_loss /= num_batches
    test_loss = test_loss ** 0.5
    print(f"Test Error: \n Avg loss: {test_loss:>8f} \n")

In [588]:
from math import exp
import math

In [589]:
def cyclical_lr(stepsize, min_lr=3e-4, max_lr=3e-3):
    
    # Scaler: we can adapt this if we do not want the triangular CLR
    scaler = lambda x: 1.

    # Lambda function to calculate the LR
    lr_lambda = lambda it: min_lr + (max_lr - min_lr) * relative(it, stepsize)

    # Additional function to see where on the cycle we are
    def relative(it, stepsize):
        cycle = math.floor(1 + it / (2 * stepsize))
        x = abs(it / stepsize - 2 * cycle + 1)
        return max(0, (1 - x)) * scaler(cycle)

    return lr_lambda

In [590]:
loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)
step_size = 4*len(dataset_train)
clr = cyclical_lr(step_size)
# scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, [clr])
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(loader_train, model, loss_fn, optimizer)
    test_loop(loader_test, model, loss_fn)
    # optimizer.lr = exp_decay(t)
print("Done!")

Epoch 1
-------------------------------


e:\Dev\Anaconda\lib\site-packages\torch\nn\modules\loss.py:96: UserWarning:

Using a target size (torch.Size([256])) that is different to the input size (torch.Size([256, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.

e:\Dev\Anaconda\lib\site-packages\torch\nn\modules\loss.py:96: UserWarning:

Using a target size (torch.Size([253])) that is different to the input size (torch.Size([253, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.

e:\Dev\Anaconda\lib\site-packages\torch\nn\modules\loss.py:96: UserWarning:

Using a target size (torch.Size([170])) that is different to the input size (torch.Size([170, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.



loss: 18.392454
Test Error: 
 Avg loss: 18.109300 

Epoch 2
-------------------------------
loss: 18.341588
Test Error: 
 Avg loss: 18.095355 

Epoch 3
-------------------------------
loss: 17.839061
Test Error: 
 Avg loss: 18.095956 

Epoch 4
-------------------------------
loss: 18.965455
Test Error: 
 Avg loss: 18.099563 

Epoch 5
-------------------------------
loss: 18.601097
Test Error: 
 Avg loss: 18.103713 

Epoch 6
-------------------------------
loss: 17.992944
Test Error: 
 Avg loss: 18.082345 

Epoch 7
-------------------------------
loss: 18.176026
Test Error: 
 Avg loss: 18.092506 

Epoch 8
-------------------------------
loss: 18.238857
Test Error: 
 Avg loss: 18.097635 

Epoch 9
-------------------------------
loss: 18.244203
Test Error: 
 Avg loss: 18.099777 

Epoch 10
-------------------------------
loss: 17.827999
Test Error: 
 Avg loss: 18.102556 

Epoch 11
-------------------------------
loss: 18.426473
Test Error: 
 Avg loss: 18.100995 

Epoch 12
-----------------

In [591]:
def SMAPE(y_true, y_pred):
    denominator = (y_true + np.abs(y_pred)) / 200.0
    diff = np.abs(y_true - y_pred) / denominator
    diff[denominator == 0] = 0.0
    return np.mean(diff)


In [592]:
x_train = x_train.to(device)
x_test = x_test.to(device)

train_pred = model(x_train)
test_pred = model(x_test)

train_score = SMAPE(y_train.cpu().detach().numpy(), train_pred.cpu().detach().numpy())
test_score = SMAPE(y_test.cpu().detach().numpy(), test_pred.cpu().detach().numpy())

print('train_score ', train_score, 'test_score', test_score)

train_score  46.557434 test_score 46.604073


In [593]:
test = test.to(device)

In [594]:
test_pred = model(test)

In [595]:
train_pred.cpu()

tensor([[334.3299],
        [320.3972],
        [249.7827],
        ...,
        [251.7216],
        [294.6108],
        [333.0201]], grad_fn=<ToCopyBackward0>)

In [596]:
unique, counts = np.unique(y_train.cpu().detach().numpy(), return_counts=True)
unique_p, counts_p = np.unique(np.round(train_pred.cpu().detach().numpy()), return_counts=True)
d_p = pd.DataFrame(index = unique_p,data = counts_p,columns=['count_pred'])
d = pd.DataFrame(index= unique,data=  counts,columns=['count_true'])
d1 = d.join(d_p)
d1 = d1.fillna(0)


In [597]:
d_p

count_pred
198.0           1
200.0           1
206.0           1
207.0           2
208.0           1
...           ...
394.0           2
395.0           1
396.0           1
397.0           2
399.0           1

[193 rows x 1 columns]

In [598]:
import plotly.express as px

fig = px.line(d1, x= d.index, y = ['count_true', 'count_pred'])
fig.show()

In [583]:
submission = pd.read_csv('sample_submission.csv')
submission.num_sold = test_pred.cpu().detach().numpy().reshape(-1)
submission.to_csv('submission.csv', index=False)